//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMercury.EffectEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectMercury.EffectEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MercuryLogoWhiteBG {
            get {
                object obj = ResourceManager.GetObject("MercuryLogoWhiteBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ParticleEffect {
            get {
                object obj = ResourceManager.GetObject("ParticleEffect", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误时，错误消息现在将写入Trace.log 的本地化字符串。
        /// </summary>
        internal static string UserInterface_AssertOperationOK_ {
            get {
                return ResourceManager.GetString("UserInterface_AssertOperationOK_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序错误 的本地化字符串。
        /// </summary>
        internal static string UserInterface_AssertOperationOK_程序错误 {
            get {
                return ResourceManager.GetString("UserInterface_AssertOperationOK_程序错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新: {0:F5} 秒 的本地化字符串。
        /// </summary>
        internal static string UserInterface_SetUpdateTime_更新___0_F5__秒 {
            get {
                return ResourceManager.GetString("UserInterface_SetUpdateTime_更新___0_F5__秒", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备就绪 的本地化字符串。
        /// </summary>
        internal static string UserInterface_uxEffectPreview_MouseUp_准备就绪 {
            get {
                return ResourceManager.GetString("UserInterface_uxEffectPreview_MouseUp_准备就绪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定你想打开这个效果吗？ 未保存的更改将会丢失. 的本地化字符串。
        /// </summary>
        internal static string UserInterface_uxLibraryListView_ItemActivate_ {
            get {
                return ResourceManager.GetString("UserInterface_uxLibraryListView_ItemActivate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string UserInterface_uxLibraryListView_ItemActivate_确认 {
            get {
                return ResourceManager.GetString("UserInterface_uxLibraryListView_ItemActivate_确认", resourceCulture);
            }
        }
    }
}
